### ISSUE TITLE
Move images from theme to pages

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-theme-photographer#1]
Hi,
it's just  a week I'm on grav, so this issue might be wrong or silly. In the home page modular/categories.html.twig template you put images into the theme and you render it as follows:

< figure>< img src="{{ theme_url }}/img/{{ category.image }}" alt=""></ figure>

so It could be a nice idea to change it as follows:

< figure>{{ page.media[category.image] }}</ figure>

to let a developer to change the images directly into the page, without overriding the theme for this. If this make sense, let me know and I will work on it.

Thank you

**Comment by rhukster** [comment]
Make sense, feel free to issue a PR and i'll take a look. Thanks!

**Comment by giansi** [comment]
Perfect I will work on it tomorrow.

**Comment by hexplor** [comment]
This actually makes sense :) Thanks :) Merged :)
